// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncrzjqerxvtdnpkysdcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jcnpqcWVyeHZ0ZG5wa3lzZGNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNDM2MDgsImV4cCI6MjA2NzkxOTYwOH0.EvshFjU2OqhpeW39ltVfFLuhUqnqXFrXRaEVBMK7uEQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});